var annotated_dup =
[
    [ "C40TextState_struct", "structC40TextState__struct.html", "structC40TextState__struct" ],
    [ "Callback", "structCallback.html", "structCallback" ],
    [ "DmtxBestLine_struct", "structDmtxBestLine__struct.html", "structDmtxBestLine__struct" ],
    [ "DmtxBresLine", "structDmtxBresLine.html", null ],
    [ "DmtxBresLine_struct", "structDmtxBresLine__struct.html", "structDmtxBresLine__struct" ],
    [ "DmtxByteList", "structDmtxByteList.html", null ],
    [ "DmtxByteList_struct", "structDmtxByteList__struct.html", "structDmtxByteList__struct" ],
    [ "DmtxChannel", "structDmtxChannel.html", null ],
    [ "DmtxChannel_struct", "structDmtxChannel__struct.html", "structDmtxChannel__struct" ],
    [ "DmtxChannelGroup", "structDmtxChannelGroup.html", null ],
    [ "DmtxChannelGroup_struct", "structDmtxChannelGroup__struct.html", "structDmtxChannelGroup__struct" ],
    [ "DmtxDecode", "structDmtxDecode.html", null ],
    [ "DmtxDecode_struct", "structDmtxDecode__struct.html", "structDmtxDecode__struct" ],
    [ "DmtxEncode", "structDmtxEncode.html", null ],
    [ "DmtxEncode_struct", "structDmtxEncode__struct.html", "structDmtxEncode__struct" ],
    [ "DmtxEncodeStream_struct", "structDmtxEncodeStream__struct.html", "structDmtxEncodeStream__struct" ],
    [ "DmtxFollow", "structDmtxFollow.html", null ],
    [ "DmtxFollow_struct", "structDmtxFollow__struct.html", "structDmtxFollow__struct" ],
    [ "DmtxImage_struct", "structDmtxImage__struct.html", "structDmtxImage__struct" ],
    [ "DmtxLogEvent_struct", "structDmtxLogEvent__struct.html", "structDmtxLogEvent__struct" ],
    [ "DmtxMessage_struct", "structDmtxMessage__struct.html", "structDmtxMessage__struct" ],
    [ "DmtxPixelLoc_struct", "structDmtxPixelLoc__struct.html", "structDmtxPixelLoc__struct" ],
    [ "DmtxPointFlow_struct", "structDmtxPointFlow__struct.html", "structDmtxPointFlow__struct" ],
    [ "DmtxQuadruplet", "structDmtxQuadruplet.html", null ],
    [ "DmtxQuadruplet_struct", "structDmtxQuadruplet__struct.html", "structDmtxQuadruplet__struct" ],
    [ "DmtxRay2_struct", "structDmtxRay2__struct.html", "structDmtxRay2__struct" ],
    [ "DmtxRegion_struct", "structDmtxRegion__struct.html", "structDmtxRegion__struct" ],
    [ "DmtxScanGrid", "structDmtxScanGrid.html", null ],
    [ "DmtxScanGrid_struct", "structDmtxScanGrid__struct.html", "structDmtxScanGrid__struct" ],
    [ "DmtxTime", "structDmtxTime.html", null ],
    [ "DmtxTime_struct", "structDmtxTime__struct.html", "structDmtxTime__struct" ],
    [ "DmtxTriplet", "structDmtxTriplet.html", null ],
    [ "DmtxTriplet_struct", "structDmtxTriplet__struct.html", "structDmtxTriplet__struct" ],
    [ "DmtxVector2_struct", "structDmtxVector2__struct.html", "structDmtxVector2__struct" ]
];