name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Doxygen
      uses: ssciwr/doxygen-install@v1
      with:
        version: "1.12.0"

    - name: Configure
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release -Ddmtx_BUILD_EXAMPLES=OFF -Ddmtx_BUILD_TESTING=OFF

    - name: Build
      run: cmake --build build --config Release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html